spring.application.name=dropbox-demo
oauth.dropbox.client-id=${OAUTH_DROPBOX_CLIENT_ID}
oauth.dropbox.client-secret=${OAUTH_DROPBOX_CLIENT_SECRET}
oauth.dropbox.redirect-url=${OAUTH_DROPBOX_REDIRECT_URL}
